function freezeMissionDefinition(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) freezeMissionDefinition(child);
  return Object.freeze(value);
}

const REFERENCE_MISSION = freezeMissionDefinition({
  id: 'reference_facility',
  world: {
    designWidth: 1100,
    designHeight: 750,
    width: 3200,
    height: 1800,
  },
  player: {
    start: { x: 500, y: 680 },
  },
  rooms: [
    {
      id: 'lobby',
      center: { x: 460, y: 590 },
      bounds: { x: 0, y: 449, w: 909, h: 301, maxXInclusive: true },
      startingSpace: true,
    },
    {
      id: 'room_a',
      center: { x: 200, y: 229 },
      bounds: { x: 0, y: 0, w: 409, h: 449 },
      startingSpace: false,
    },
    {
      id: 'corridor',
      center: { x: 589, y: 229 },
      bounds: { x: 409, y: 0, w: 360, h: 449, maxXInclusive: true },
      startingSpace: false,
    },
    {
      id: 'room_bc',
      center: { x: 930, y: 229 },
      bounds: { x: 769, y: 0, w: 331, h: 449, minXExclusive: true },
      startingSpace: false,
    },
    {
      id: 'room_f',
      center: { x: 991, y: 590 },
      bounds: { x: 909, y: 449, w: 191, h: 301, minXExclusive: true },
      startingSpace: false,
    },
  ],
  connectors: [
    {
      id: 'corridor_left_door',
      kind: 'door',
      rooms: ['lobby', 'corridor'],
      position: { x: 270, y: 449 },
      doorId: 'corridor_left_door',
      navNodeId: 'gap_corr_left',
      apertureIds: ['corridor_left_door_n', 'corridor_left_door_s'],
    },
    {
      id: 'corridor_right_door',
      kind: 'door',
      rooms: ['lobby', 'corridor'],
      position: { x: 819, y: 449 },
      doorId: 'corridor_right_door',
      navNodeId: 'gap_corr_right',
      apertureIds: ['corridor_right_door_n', 'corridor_right_door_s'],
    },
    {
      id: 'room_a_east_door',
      kind: 'door',
      rooms: ['room_a', 'corridor'],
      position: { x: 409, y: 295 },
      doorId: 'room_a_east_door',
      navNodeId: 'gap_room_a',
      apertureIds: ['room_a_east_door_e', 'room_a_east_door_w'],
    },
    {
      id: 'room_bc_divider_door',
      kind: 'door',
      rooms: ['corridor', 'room_bc'],
      position: { x: 769, y: 210 },
      doorId: 'room_bc_divider_door',
      navNodeId: 'gap_room_bc',
      apertureIds: ['room_bc_divider_door_e', 'room_bc_divider_door_w'],
    },
    {
      id: 'room_f_west_door',
      kind: 'door',
      rooms: ['lobby', 'room_f'],
      position: { x: 909, y: 590 },
      doorId: 'room_f_west_door',
      navNodeId: 'gap_room_f',
      apertureIds: ['room_f_west_door_e', 'room_f_west_door_w'],
    },
    {
      id: 'room_a_west_window',
      kind: 'window',
      rooms: ['room_a', 'exterior'],
      position: { x: 9, y: 190 },
      windowId: 'room_a_west_window',
      apertureIds: ['room_a_west_window_moonlight'],
    },
    {
      id: 'room_bc_east_window',
      kind: 'window',
      rooms: ['room_bc', 'exterior'],
      position: { x: 1091, y: 190 },
      windowId: 'room_bc_east_window',
      apertureIds: ['room_bc_east_window_moonlight'],
    },
    {
      id: 'primary_entry_gap',
      kind: 'opening',
      rooms: ['lobby', 'exterior'],
      position: { x: 500, y: 741 },
    },
  ],
  geometry: {
    walls: [
      { id: 'wall_0', x: 0, y: 0, w: 1100, h: 18 },
      { id: 'wall_1', x: 0, y: 732, w: 430, h: 18 },
      { id: 'wall_2', x: 570, y: 732, w: 530, h: 18 },
      { id: 'wall_3', x: 0, y: 0, w: 18, h: 160 },
      { id: 'wall_4', x: 0, y: 220, w: 18, h: 530 },
      { id: 'wall_5', x: 1082, y: 0, w: 18, h: 160 },
      { id: 'wall_6', x: 1082, y: 220, w: 18, h: 530 },
      { id: 'wall_7', x: 18, y: 440, w: 202, h: 18 },
      { id: 'wall_8', x: 320, y: 440, w: 458, h: 18 },
      { id: 'wall_9', x: 860, y: 440, w: 222, h: 18 },
      { id: 'wall_10', x: 400, y: 18, w: 18, h: 232 },
      { id: 'wall_11', x: 400, y: 340, w: 18, h: 100 },
      { id: 'wall_12', x: 760, y: 18, w: 18, h: 142 },
      { id: 'wall_13', x: 760, y: 260, w: 18, h: 180 },
      { id: 'wall_14', x: 900, y: 440, w: 18, h: 100 },
      { id: 'wall_15', x: 900, y: 640, w: 18, h: 92 },
    ],
    wallGapExits: [
      { id: 'room_a_window_exit', connectorId: 'room_a_west_window', activated: false },
      { id: 'room_bc_window_exit', connectorId: 'room_bc_east_window', activated: false },
    ],
  },
  doors: [
    {
      id: 'corridor_left_door',
      connectorId: 'corridor_left_door',
      x: 220, y: 446, w: 100, h: 6,
      orientation: 'horizontal',
      material: 'wood',
      defaultState: 'closed',
    },
    {
      id: 'corridor_right_door',
      connectorId: 'corridor_right_door',
      x: 778, y: 446, w: 82, h: 6,
      orientation: 'horizontal',
      material: 'wood',
      defaultState: 'closed',
    },
    {
      id: 'room_a_east_door',
      connectorId: 'room_a_east_door',
      x: 406, y: 250, w: 6, h: 90,
      orientation: 'vertical',
      material: 'wood',
      defaultState: 'closed',
    },
    {
      id: 'room_bc_divider_door',
      connectorId: 'room_bc_divider_door',
      x: 766, y: 160, w: 6, h: 100,
      orientation: 'vertical',
      material: 'wood',
      defaultState: 'closed',
    },
    {
      id: 'room_f_west_door',
      connectorId: 'room_f_west_door',
      x: 900, y: 540, w: 18, h: 100,
      orientation: 'vertical',
      material: 'metal',
      defaultState: 'closed',
    },
  ],
  windows: [
    {
      id: 'room_a_west_window',
      connectorId: 'room_a_west_window',
      x: 7.5, y: 160, w: 3, h: 60,
      orientation: 'vertical',
      material: 'glass',
      defaultState: 'intact',
    },
    {
      id: 'room_bc_east_window',
      connectorId: 'room_bc_east_window',
      x: 1089.5, y: 160, w: 3, h: 60,
      orientation: 'vertical',
      material: 'glass',
      defaultState: 'intact',
    },
  ],
  lighting: {
    globalAmbient: 0,
    externalLightAvailable: true,
    zones: [
      { id: 'lobby_lamp_spill', x: 320, y: 458, w: 380, h: 170, ambient: 0.10 },
      { id: 'entry_dim_spill', x: 430, y: 640, w: 140, h: 92, ambient: 0.08 },
      { id: 'corridor_left_threshold_spill', x: 220, y: 430, w: 100, h: 44, ambient: 0.06 },
      { id: 'corridor_right_threshold_spill', x: 778, y: 430, w: 82, h: 44, ambient: 0.06 },
    ],
    lamps: [
      { id: 'lamp_1', roomId: 'room_a', x: 200, y: 18, wallSide: 'N', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_2', roomId: 'corridor', x: 580, y: 18, wallSide: 'N', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_3', roomId: 'room_bc', x: 920, y: 18, wallSide: 'N', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_4', roomId: 'room_a', x: 200, y: 440, wallSide: 'S', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_5', roomId: 'corridor', x: 580, y: 440, wallSide: 'S', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_6', roomId: 'room_bc', x: 920, y: 440, wallSide: 'S', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_7', roomId: 'lobby', x: 350, y: 458, wallSide: 'N', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_8', roomId: 'lobby', x: 700, y: 458, wallSide: 'N', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_9', roomId: 'lobby', x: 350, y: 732, wallSide: 'S', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_10', roomId: 'lobby', x: 700, y: 732, wallSide: 'S', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_11', roomId: 'lobby', x: 18, y: 630, wallSide: 'W', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
      { id: 'lamp_12', roomId: 'room_f', x: 1082, y: 590, wallSide: 'E', radius: 900, intensity: 1, falloffPower: 1.45, color: '#ffdc96', active: true },
    ],
    apertures: [
      { id: 'room_a_west_window_moonlight', connectorId: 'room_a_west_window', kind: 'window', x: 18, y: 190, direction: 'E', width: 70, range: 360, intensity: 0.24, falloffPower: 1.05, spreadRadians: 0.95, open: true, requiresExternalLight: true },
      { id: 'room_bc_east_window_moonlight', connectorId: 'room_bc_east_window', kind: 'window', x: 1082, y: 190, direction: 'W', width: 70, range: 360, intensity: 0.24, falloffPower: 1.05, spreadRadians: 0.95, open: true, requiresExternalLight: true },
      { id: 'corridor_left_door_n', connectorId: 'corridor_left_door', kind: 'door', x: 270, y: 440, direction: 'N', width: 100, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'corridor_left_door_s', connectorId: 'corridor_left_door', kind: 'door', x: 270, y: 458, direction: 'S', width: 100, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'corridor_right_door_n', connectorId: 'corridor_right_door', kind: 'door', x: 819, y: 440, direction: 'N', width: 82, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'corridor_right_door_s', connectorId: 'corridor_right_door', kind: 'door', x: 819, y: 458, direction: 'S', width: 82, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'room_a_east_door_e', connectorId: 'room_a_east_door', kind: 'door', x: 418, y: 295, direction: 'E', width: 90, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'room_a_east_door_w', connectorId: 'room_a_east_door', kind: 'door', x: 400, y: 295, direction: 'W', width: 90, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'room_bc_divider_door_e', connectorId: 'room_bc_divider_door', kind: 'door', x: 778, y: 210, direction: 'E', width: 100, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'room_bc_divider_door_w', connectorId: 'room_bc_divider_door', kind: 'door', x: 760, y: 210, direction: 'W', width: 100, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'room_f_west_door_e', connectorId: 'room_f_west_door', kind: 'door', x: 918, y: 590, direction: 'E', width: 100, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
      { id: 'room_f_west_door_w', connectorId: 'room_f_west_door', kind: 'door', x: 900, y: 590, direction: 'W', width: 100, range: 320, intensity: 0.62, falloffPower: 0.7, spreadRadians: 1.1, open: false },
    ],
  },
  objective: {
    pickupRule: { excludeStartingSpaces: true },
    exfilPoints: [
      { id: 'primary_entry_exfil', connectorId: 'primary_entry_gap', type: 'primary', active: false, discovered: true },
    ],
  },
  enemies: {
    spawns: [
      {
        id: 'enemy_1',
        x: 580, y: 100, angle: Math.PI, targetAngle: Math.PI,
        archetype: 'melee',
        visionAngle: Math.PI * 2 / 3, sightRange: Infinity, proximityRadius: 50,
        patrolSpeed: 1.5,
        patrolRoute: [],
      },
      {
        id: 'enemy_2',
        x: 500, y: 590, angle: 0, targetAngle: 0,
        archetype: 'melee',
        visionAngle: Math.PI * 2 / 3, sightRange: Infinity, proximityRadius: 50,
        patrolSpeed: 1.5,
        patrolRoute: [
          { x: 420, y: 590, pauseFrames: 240, sweep: 0, sweepSpeed: 0 },
          { x: 580, y: 590, pauseFrames: 240, sweep: 0, sweepSpeed: 0 },
        ],
      },
      {
        id: 'enemy_3',
        x: 200, y: 229, angle: 0, targetAngle: 0,
        archetype: 'shooter',
        visionAngle: Math.PI * 2 / 3, sightRange: Infinity, proximityRadius: 50,
        patrolSpeed: 1.5,
        shootingRange: 360,
        shootingRangeTolerance: 40,
        shotCooldownFrames: 75,
        shotSpeed: 25,
        aimSpreadRadians: 0.16,
        patrolRoute: [
          { x: 200, y: 229, pauseFrames: 60, sweep: Math.PI, sweepSpeed: 0.008 },
          { x: 409, y: 295, pauseFrames: 0, sweep: 0, sweepSpeed: 0 },
          { x: 589, y: 229, pauseFrames: 0, sweep: 0, sweepSpeed: 0 },
          { x: 769, y: 210, pauseFrames: 0, sweep: 0, sweepSpeed: 0 },
          { x: 930, y: 229, pauseFrames: 60, sweep: Math.PI, sweepSpeed: 0.008 },
          { x: 769, y: 210, pauseFrames: 0, sweep: 0, sweepSpeed: 0 },
          { x: 589, y: 229, pauseFrames: 0, sweep: 0, sweepSpeed: 0 },
          { x: 409, y: 295, pauseFrames: 0, sweep: 0, sweepSpeed: 0 },
        ],
      },
    ],
    navigation: {
      nodes: [
        { id: 'lobby', roomId: 'lobby' },
        { id: 'gap_corr_left', connectorId: 'corridor_left_door' },
        { id: 'gap_corr_right', connectorId: 'corridor_right_door' },
        { id: 'corridor', roomId: 'corridor' },
        { id: 'gap_room_a', connectorId: 'room_a_east_door' },
        { id: 'room_a', roomId: 'room_a' },
        { id: 'gap_room_bc', connectorId: 'room_bc_divider_door' },
        { id: 'room_bc', roomId: 'room_bc' },
        { id: 'gap_room_f', connectorId: 'room_f_west_door' },
        { id: 'room_f', roomId: 'room_f' },
      ],
      edges: [
        ['lobby', 'gap_corr_left'],
        ['gap_corr_left', 'corridor'],
        ['lobby', 'gap_corr_right'],
        ['gap_corr_right', 'gap_room_f'],
        ['gap_room_f', 'room_f'],
        ['corridor', 'gap_room_a'],
        ['gap_room_a', 'room_a'],
        ['corridor', 'gap_room_bc'],
        ['gap_room_bc', 'room_bc'],
      ],
    },
  },
  sound: {
    rooms: ['lobby', 'room_a', 'corridor', 'room_bc', 'room_f'],
    portals: [
      'corridor_left_door',
      'corridor_right_door',
      'room_a_east_door',
      'room_bc_divider_door',
      'room_f_west_door',
    ],
  },
});
